#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Tom F. <tomf@tomtomtech.net> (https://github.com/tomtom215)
#
# Developer Certificate of Origin (DCO) check over a commit range.
#
#   scripts/check_dco.sh <base-sha> <head-sha>
#
# Two checks run over every non-merge commit in base..head:
#
#   1. Sign-off  — the commit message must carry a `Signed-off-by:` trailer
#      whose email matches the commit's git author email.
#   2. Authorship — the git author must be a human identity, not an AI
#      assistant's service account. A sign-off is an assertion by a person;
#      a commit authored by a tool identity cannot carry a meaningful one.
#      See PROVENANCE.md §3.2 for why this check exists.
#
# Two exact-identity exemptions, both from PROVENANCE.md §3.2:
#
#   * Dependabot. A version bump carries no authored content to certify; the
#     human act is the review and merge, which branch protection requires.
#   * The Benchmarks workflow's own commit, which regenerates the two book
#     pages it names below and nothing else. It is generated by this
#     repository's code from measurements, pushed with GITHUB_TOKEN — which
#     creates no workflow run, so no other gate ever sees it — and checked
#     here by benchmarks.yml itself before the push. The exemption holds only
#     while the commit touches nothing but those pages; a bot commit that
#     reaches any other file fails.
#
# This used to be the body of a step in .github/workflows/dco.yml. It moved
# here on 2026-09-10 so benchmarks.yml can run the same check over the commit
# it is about to push (scripts/check_gate_reachability.py, rule R3), and so
# dco.yml — which now runs on pushes to main as well as pull requests —
# grades one implementation rather than two copies. Plain git + bash rather
# than a third-party action: this gates every contribution, so it should not
# depend on a supply chain outside the repository.
#
# Exit codes: 0 every commit passes, 1 a commit fails, 2 usage.

set -euo pipefail

if [ $# -ne 2 ]; then
    echo "usage: $0 <base-sha> <head-sha>" >&2
    exit 2
fi
BASE_SHA=$1
HEAD_SHA=$2

# Author emails that identify a tool rather than a person. Extend this list
# if the project adopts another assistant.
NON_HUMAN='^(noreply@anthropic\.com|.*\[bot\]@users\.noreply\.github\.com)$'

# Exemptions are by exact author identity, not by the [bot] suffix, so no
# other automation inherits them.
DEPENDABOT='^49699333\+dependabot\[bot\]@users\.noreply\.github\.com$'
BENCH_BOT='^41898282\+github-actions\[bot\]@users\.noreply\.github\.com$'
# The only files the Benchmarks workflow commits (benchmarks.yml, the
# "Commit benchmark results to book" step). One path per line.
BENCH_PAGES='^book/src/reference/(benchmarks\.md|benchmark-dashboard\.html)$'

failed=0

# %H<TAB>%ae<TAB>%an — one line per non-merge commit in the range.
# `--no-merges` skips merge commits, which have no authored content.
while IFS=$'\t' read -r sha author_email author_name; do
    [ -n "$sha" ] || continue

    subject=$(git log -1 --format='%s' "$sha")

    if printf '%s' "$author_email" | grep -Eq "$DEPENDABOT"; then
        echo "  ok  ${sha:0:8}  dependabot (exempt: dependency bump, see PROVENANCE.md 3.2)"
        continue
    fi

    if printf '%s' "$author_email" | grep -Eq "$BENCH_BOT"; then
        # Every path the commit touches must be one of the generated pages.
        outside=$(git diff-tree --no-commit-id --name-only -r "$sha" \
            | grep -Ev "$BENCH_PAGES" || true)
        touched=$(git diff-tree --no-commit-id --name-only -r "$sha" | wc -l)
        if [ -z "$outside" ] && [ "$touched" -gt 0 ]; then
            echo "  ok  ${sha:0:8}  benchmarks workflow (exempt: generated benchmark pages only, see PROVENANCE.md 3.2)"
            continue
        fi
        echo "::error::${sha:0:8} (\"$subject\") is authored by the Benchmarks workflow's identity <$author_email>"
        echo "         but touches files outside the generated benchmark pages:"
        printf '           %s\n' $outside
        echo "         The exemption covers book/src/reference/benchmarks.md and"
        echo "         benchmark-dashboard.html and nothing else. See PROVENANCE.md section 3.2."
        failed=1
        continue
    fi

    # ── 1. Authorship ────────────────────────────────────────────────────────
    if printf '%s' "$author_email" | grep -Eqi "$NON_HUMAN"; then
        echo "::error::${sha:0:8} (\"$subject\") is authored by a non-human identity <$author_email>."
        echo "         A DCO sign-off is an assertion by a person. Re-author this commit"
        echo "         as yourself and credit the assistant with a Co-Authored-By trailer."
        echo "         See PROVENANCE.md section 3.2."
        failed=1
        continue
    fi

    # ── 2. Sign-off ──────────────────────────────────────────────────────────
    # Accept a trailer whose email matches the author's, case-insensitively.
    if git log -1 --format='%B' "$sha" \
         | grep -Eqi "^[[:space:]]*Signed-off-by:[[:space:]]+.+<${author_email//./\\.}>[[:space:]]*$"; then
        echo "  ok  ${sha:0:8}  $author_name <$author_email>"
    else
        echo "::error::${sha:0:8} (\"$subject\") has no Signed-off-by trailer matching <$author_email>."
        failed=1
    fi
done < <(git log --no-merges --format='%H%x09%ae%x09%an' "$BASE_SHA..$HEAD_SHA")

if [ "$failed" -ne 0 ]; then
    cat <<'REMEDY'

─────────────────────────────────────────────────────────────────────
This project requires the Developer Certificate of Origin (see ./DCO).

Sign off new commits as you make them:

    git commit -s -m "your message"

To add a sign-off to the last commit:

    git commit --amend -s --no-edit && git push --force-with-lease

To sign off every commit in this branch:

    git rebase --signoff origin/main && git push --force-with-lease

If a commit is authored by an assistant identity, reset the author
at the same time:

    git rebase origin/main \
      --exec 'git commit --amend --no-edit --reset-author -s'
─────────────────────────────────────────────────────────────────────
REMEDY
    exit 1
fi

echo "All commits carry a matching sign-off from a human author."
