#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Tom F.
"""Render benches/results/cross-language-*.json into an mdbook page.

Every figure on the page is computed here from the result files. Nothing is
typed in by hand, so the page cannot drift from the measurement it describes.
"""

from __future__ import annotations

import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
RESULTS = REPO / "benches" / "results"
OUT = REPO / "book" / "src" / "reference" / "cross-language-benchmarks.md"

RUST = "rust-a2a-protocol-server"
PY = "official-python-a2a-sdk"
FLOOR = "floor"

# A model call is what an agent turn actually spends its time on. These bounds
# are deliberately wide and are used only to put the measured SDK cost in
# proportion; nothing on the page depends on their precision.
TURN_FAST_S = 1.0
TURN_SLOW_S = 30.0


def load(name: str) -> dict:
    path = RESULTS / f"cross-language-{name}.json"
    if not path.exists():
        sys.exit(f"missing {path}; run benches/scripts/cross_language_python.sh first")
    return json.loads(path.read_text())


def cpu(doc: dict, target: str) -> float:
    return doc["results"][target]["cpu"]["server_cpu_us_per_request"]


def p50(doc: dict, target: str) -> float:
    return doc["results"][target]["sequential"]["median_of_trial_medians_us"]


def rps(doc: dict, target: str) -> float:
    return doc["results"][target]["concurrent"]["median_throughput_rps"]


def main() -> int:
    pinned = load("pinned")
    default = load("default")
    env = pinned["environment"]
    method = pinned["method"]

    r_cpu, p_cpu = cpu(pinned, RUST), cpu(pinned, PY)
    delta_ms = (p_cpu - r_cpu) / 1000.0
    ratio = p_cpu / r_cpu

    pct_fast = 100 * (delta_ms / 1000.0) / TURN_FAST_S
    pct_slow = 100 * (delta_ms / 1000.0) / TURN_SLOW_S

    lines: list[str] = []
    w = lines.append

    w("<!-- SPDX-License-Identifier: Apache-2.0 -->")
    w("<!-- Auto-generated by benches/scripts/generate_cross_language_page.py"
      " — do not edit manually -->")
    w("# Cross-Language Benchmark: A2A Layer Cost")
    w("")
    w("## What this measures, and what it does not")
    w("")
    w("This page answers one narrow question: **what does the A2A protocol layer")
    w("itself cost to run?** It compares this Rust SDK's server against the")
    w("official Python `a2a-sdk` server on an identical echo workload.")
    w("")
    w("It is **not** a recommendation to change SDKs, and it is not evidence that")
    w("an agent built on the official Python SDK is slow. The workload here is an")
    w("echo with no application work at all, which is the case that shows protocol")
    w("overhead most starkly, because there is nothing else in the request to")
    w("dilute it. A real agent turn is dominated by model inference.")
    w("")
    w(f"Put in proportion: the measured difference is **{delta_ms:.2f} ms of CPU per")
    w(f"request**. Against an agent turn spending {TURN_FAST_S:.0f}–{TURN_SLOW_S:.0f} s")
    w(f"in a model, that is **{pct_slow:.3f} %–{pct_fast:.2f} % of the turn**. No single")
    w("agent will notice it. Nothing here argues otherwise.")
    w("")
    w("Where it does matter is **aggregation**. Protocol cost is paid per request")
    w("regardless of what the agent does, so it scales with traffic rather than with")
    w("model latency. The same throughput costs materially different amounts of CPU:")
    w("")
    w("| Sustained A2A traffic | CPU spent on A2A handling — this SDK | CPU spent on A2A handling — official Python SDK |")
    w("|---|---|---|")
    for load_rps in (10, 100, 1000, 10000):
        w(f"| {load_rps:,} req/s | {r_cpu * load_rps / 1e6:.3f} cores | "
          f"{p_cpu * load_rps / 1e6:.2f} cores |")
    w("")
    w("That is the shape of the result: irrelevant inside one agent, and the whole")
    w("cost model for anything that terminates A2A traffic on behalf of many.")
    w("")

    w("## Headline: CPU consumed per request")
    w("")
    w("The primary figure, because it is what a capacity argument actually rests on.")
    w("Latency cannot distinguish work from waiting — a server blocked on a poll and")
    w("one burning CPU can post the same round-trip time. This is the server's own")
    w("`utime + stime` from `/proc`, divided by requests served.")
    w("")
    w("| Server | CPU per request | Requests sampled | Clock-tick quantisation error |")
    w("|---|---|---|---|")
    for label, title in ((RUST, "This SDK (Rust)"), (PY, "Official `a2a-sdk` (Python)")):
        c = pinned["results"][label]["cpu"]
        w(f"| {title} | **{c['server_cpu_us_per_request']:,.1f} µs** | "
          f"{c['requests']:,} | {c['quantisation_error_pct']:.2f} % |")
    w("")
    w(f"**{ratio:.1f}× the CPU per request**, or {p_cpu - r_cpu:,.0f} µs more, on the")
    w("pinned configuration described below.")
    w("")

    w("## Latency and throughput")
    w("")
    w("Both configurations are shown because either alone invites a misreading.")
    w("`pinned` confines each server to a single distinct core, which answers the")
    w("objection that a multi-threaded Rust server was given four cores while one")
    w("uvicorn worker got one. `default` runs each server exactly as its own")
    w("documentation says to.")
    w("")
    w("Note that the Rust server is **slower unpinned than pinned**, and the Python")
    w("server is unaffected by pinning — it is single-threaded and CPU-bound, so")
    w("confining it changes nothing. The pinned configuration is not favourable to")
    w("this SDK; if anything it is the opposite.")
    w("")
    for name, doc in (("pinned", pinned), ("default", default)):
        w(f"### `{name}`")
        w("")
        pin = doc["environment"]["cpu_pinning"]
        if "''" in pin or pin == "none":
            w("No CPU pinning: every process free to run on any core, as each")
            w("server's own documentation describes running it.")
        else:
            w(f"`{pin}`")
        w("")
        w("| Server | p50 | p95 | p99 | trial-to-trial p50 spread | throughput (50 connections) |")
        w("|---|---|---|---|---|---|")
        for label, title in (
            (RUST, "This SDK (Rust)"),
            (PY, "Official `a2a-sdk` (Python)"),
            (FLOOR, "_floor — no A2A work_"),
        ):
            s = doc["results"][label]["sequential"]
            t = s["trials"][0]
            thr = (
                f"{rps(doc, label):,.0f} req/s"
                if label != FLOOR
                else "_not comparable — see below_"
            )
            w(f"| {title} | {s['median_of_trial_medians_us']:,.1f} µs | {t['p95_us']:,.1f} µs | "
              f"{t['p99_us']:,.1f} µs | {s['trial_median_min_us']:,.1f}–{s['trial_median_max_us']:,.1f} µs | {thr} |")
        w("")

    w("### The floor row")
    w("")
    w("`floor` is a server that returns a pre-baked constant and does no A2A work.")
    w("It exists to separate SDK cost from the cost of the client, the loopback")
    w("stack and the kernel, which sit in every number on this page. Because that")
    w("shared cost is present in both real servers, **the ratio of two end-to-end")
    w("latencies understates the ratio of the servers' own handling cost.**")
    w("")
    f_p50 = p50(pinned, FLOOR)
    w(f"Subtracting the floor from the pinned p50 figures leaves "
      f"{p50(pinned, RUST) - f_p50:,.1f} µs against {p50(pinned, PY) - f_p50:,.1f} µs — a")
    w(f"{(p50(pinned, PY) - f_p50) / (p50(pinned, RUST) - f_p50):.0f}× ratio, against")
    w(f"{ratio:.1f}× on CPU. The two measure different things: floor-subtracted")
    w("latency isolates protocol handling above a bare HTTP round trip, while CPU")
    w("per request includes the server's share of kernel and network work. The CPU")
    w("figure is the conservative one, and it is the one quoted above.")
    w("")
    w("The floor's **throughput** is deliberately omitted. Under concurrency it")
    w("measures its own crude thread-per-connection ceiling, not a floor, so it")
    w("bounds nothing and must not be compared against the real servers.")
    w("")

    w("## Method")
    w("")
    w("One shared raw-socket client sends **byte-identical, pre-serialized HTTP**")
    w("over a warm keep-alive loopback connection to every target. Only the server")
    w("differs. Driving each server with its own SDK's client would measure that SDK")
    w("on both sides of the comparison and make the two legs incomparable.")
    w("")
    w("Both servers already existed for interoperability testing and share an echo")
    w("contract — `Echo: <text>` returned as a completed task artifact. Neither was")
    w("written for this benchmark:")
    w("")
    w("- this SDK: `examples/echo-agent`")
    w("- official SDK: `itk/agents/python-sdk/agent.py`, on `a2a-sdk`")
    w("")
    w("| Parameter | Value |")
    w("|---|---|")
    w(f"| Request body | {method['request_bytes']} bytes, `SendMessage`, `A2A-Version: 1.0` |")
    w(f"| Warmup per trial | {method['warmup_per_trial']:,} requests (discarded) |")
    w(f"| Measured per trial | {method['iterations_per_trial']:,} requests |")
    w(f"| Trials per configuration | {method['trials']}, each against a freshly started server |")
    w(f"| Concurrency test | {method['concurrency']} connections × "
      f"{method['concurrent_requests_per_connection']} requests |")
    w(f"| Percentile rule | {method['percentile_rule']} |")
    w("")
    w("The Python server runs uvicorn's **fast path**: `uvicorn[standard]` supplies")
    w("uvloop and httptools, and uvicorn's default `loop`/`http` setting of `auto`")
    w("selects them. The runner asserts both are installed and refuses to produce a")
    w("result without them, because measuring plain asyncio with `h11` would")
    w("understate the official SDK and make this a strawman.")
    w("")

    w("## What remains uncontrolled")
    w("")
    w("Stated so that a reader can discount the result appropriately rather than")
    w("discover the caveats later.")
    w("")
    rb_r = pinned["results"][RUST]["sequential"]["trials"][0]["response_bytes"]
    rb_p = pinned["results"][PY]["sequential"]["trials"][0]["response_bytes"]
    w(f"- **Response sizes still differ**: {rb_r} bytes from this SDK against {rb_p}")
    w("  from the official one. The request sends `historyLength: 0`, which removes")
    w("  the largest difference — the Python agent otherwise echoes the inbound")
    w("  message back in `history` — but a timestamp and artifact naming remain.")
    w("  Some small part of the gap is payload size, not protocol handling.")
    w("- **Loopback only.** No real network, so this isolates SDK cost rather than")
    w("  reproducing deployment latency. Over a real link, both numbers move toward")
    w("  the network's.")
    w("- **One uvicorn worker.** A production Python deployment would run several")
    w("  behind a process manager, multiplying its throughput roughly by worker")
    w("  count at a proportional cost in cores and memory. The per-request CPU cost,")
    w("  which is the headline figure, does not improve with more workers.")
    w("- **Echo workload.** No model call, no I/O, no business logic. This maximises")
    w("  the visible share of protocol overhead by design.")
    w("- **Shared container.** Absolute figures are specific to the host below.")
    w("  Trial-to-trial spread is reported so run-to-run noise is visible.")
    w("- **In-memory task stores** on both sides, growing for the run's duration.")
    w("  Trial medians are stable across trials, so no drift was observed at this")
    w("  scale, but neither server was measured against a persistent store.")
    w("")

    w("## Environment")
    w("")
    w("| | |")
    w("|---|---|")
    w(f"| Generated | {pinned['generated_utc']} |")
    w(f"| CPU | {env['cpu_model']} |")
    w(f"| Logical cores | {env['logical_cpus']} |")
    w(f"| Kernel | {env['kernel']} |")
    w(f"| Platform | {env['platform']} |")
    w(f"| Load average at run | {', '.join(f'{x:.2f}' for x in env['loadavg'])} |")
    w(f"| rustc | {env['rustc']} |")
    w(f"| Python | {env['python']} |")
    w(f"| Build profile | `--release` (Rust) |")
    w(f"| Repository commit | `{env['git_commit']}` |")
    w(f"| Working tree clean | {'yes' if not env['git_dirty'] else 'NO — results not reproducible'} |")
    w("")
    key = [
        pkg for pkg in env["python_packages"]
        if pkg.split("==")[0].lower()
        in {"a2a-sdk", "uvicorn", "uvloop", "httptools", "starlette", "pydantic", "httpx"}
    ]
    w(f"Python packages (full resolved set of {len(env['python_packages'])} recorded in the result file):")
    w("")
    # Tagged: an untagged fence is compiled as Rust by rustdoc once the page is
    # registered in book-tests, which `scripts/check_book_code.sh` enforces.
    w("```text")
    for pkg in sorted(key):
        w(pkg)
    w("```")
    w("")

    w("## Reproducing this")
    w("")
    w("```bash")
    w("benches/scripts/cross_language_python.sh")
    w("benches/scripts/generate_cross_language_page.py")
    w("```")
    w("")
    w("The runner builds both servers, pins the Python environment from")
    w("`benches/requirements-cross-language.txt`, runs both CPU configurations, and")
    w("writes `benches/results/cross-language-{pinned,default}.json`. Those files")
    w("carry the full raw distributions and complete provenance, including the")
    w("resolved dependency set and the repository commit. This page is generated")
    w("from them and contains no hand-entered figures.")
    w("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(REPO)} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
