#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Tom F.
#
# Generate a benchmark results page for the mdbook from criterion JSON output.
#
# Usage:
#   ./benches/scripts/generate_book_page.sh
#
# Reads criterion's estimates.json files from target/criterion/ and produces
# a Markdown page at book/src/reference/benchmarks.md suitable for mdbook.
#
# Criterion converts group name slashes to underscores in directory names:
#   benchmark_group("transport/jsonrpc/send") → target/criterion/transport_jsonrpc_send/
#
# Prerequisites:
#   - Run benchmarks first: cargo bench -p a2a-benchmarks
#   - python3 (for JSON parsing)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CRITERION_DIR="$REPO_ROOT/target/criterion"
OUTPUT_FILE="$REPO_ROOT/book/src/reference/benchmarks.md"
TIMESTAMP="$(date -u +%Y-%m-%d\ %H:%M\ UTC)"

if [ ! -d "$CRITERION_DIR" ]; then
    echo "Error: No criterion results found at $CRITERION_DIR"
    echo "Run benchmarks first: cargo bench -p a2a-benchmarks"
    exit 1
fi

# ── Helper: extract median from criterion estimates.json ──────────────────

# Extracts the median point estimate in human-readable units.
# Arguments: $1 = path to estimates.json
# Output: "123.4 µs" or "1.23 ms" or "456 ns"
extract_median() {
    local est_file="$1"
    if [ ! -f "$est_file" ]; then
        echo "—"
        return
    fi
    python3 -c "
import json
with open('$est_file') as f:
    d = json.load(f)
ns = d['median']['point_estimate']
if ns >= 1_000_000:
    print(f'{ns / 1_000_000:.2f} ms')
elif ns >= 1_000:
    print(f'{ns / 1_000:.1f} µs')
else:
    print(f'{ns:.0f} ns')
" 2>/dev/null || echo "—"
}

# Extracts the median point estimate as raw nanoseconds.
extract_median_ns() {
    local est_file="$1"
    if [ ! -f "$est_file" ]; then
        echo "0"
        return
    fi
    python3 -c "
import json
with open('$est_file') as f:
    d = json.load(f)
print(int(d['median']['point_estimate']))
" 2>/dev/null || echo "0"
}

# ── Helper: emit a results table for all matching criterion directories ───

# Arguments: $1 = glob pattern prefix (matched against top-level criterion dirs)
#            $2 = "time" or "count" (display mode)
# Criterion structure: target/criterion/<group_name>/<bench_name>/new/estimates.json
# For parameterized benchmarks: target/criterion/<group_name>/<bench_name>/<param>/new/estimates.json
emit_table() {
    local prefix="$1"
    local mode="${2:-time}"
    local found=false

    # Collect all estimates.json files under matching directories
    local results=()
    for dir in "$CRITERION_DIR"/${prefix}*/; do
        [ -d "$dir" ] || continue
        while IFS= read -r est; do
            results+=("$est")
        done < <(find "$dir" -name "estimates.json" -path "*/new/*" 2>/dev/null | sort)
    done

    if [ ${#results[@]} -eq 0 ]; then
        return
    fi

    if [ "$mode" = "count" ]; then
        printf "| Benchmark | Value |\n" >> "$OUTPUT_FILE"
        printf "|-----------|-------|\n" >> "$OUTPUT_FILE"
    else
        printf "| Benchmark | Median |\n" >> "$OUTPUT_FILE"
        printf "|-----------|--------|\n" >> "$OUTPUT_FILE"
    fi

    for est in "${results[@]}"; do
        rel="${est#$CRITERION_DIR/}"
        bench_name="${rel%/new/estimates.json}"
        if [ "$mode" = "count" ]; then
            raw_ns=$(extract_median_ns "$est")
            if [ "$raw_ns" = "0" ]; then
                printf "| \`%s\` | — |\n" "$bench_name" >> "$OUTPUT_FILE"
            else
                printf "| \`%s\` | %s |\n" "$bench_name" "$raw_ns" >> "$OUTPUT_FILE"
            fi
        else
            median=$(extract_median "$est")
            printf "| \`%s\` | %s |\n" "$bench_name" "$median" >> "$OUTPUT_FILE"
        fi
    done

    echo "" >> "$OUTPUT_FILE"
}

# ── Generate the page ─────────────────────────────────────────────────────

cat > "$OUTPUT_FILE" <<'HEADER'
<!-- SPDX-License-Identifier: Apache-2.0 -->
<!-- Auto-generated by benches/scripts/generate_book_page.sh — do not edit manually -->

# Benchmark Results

Performance measurements for the `a2a-protocol-sdk` Rust implementation,
generated by [Criterion.rs](https://github.com/bheisler/criterion.rs) statistical
benchmarking.

> **Note**: These numbers were collected on CI runners (`ubuntu-latest`). Absolute
> values will vary by hardware. Use these for **relative comparisons** between
> operations and for **regression detection** across releases — not as guarantees
> of production performance on your specific hardware.
>
> To reproduce on your own machine: `cargo bench -p a2a-benchmarks`

HEADER

printf "**Last updated:** %s  \n" "$TIMESTAMP" >> "$OUTPUT_FILE"
printf "**Rust version:** %s  \n" "$(rustc --version 2>/dev/null || echo 'unknown')" >> "$OUTPUT_FILE"
printf "**Platform:** %s  \n\n" "$(uname -s)-$(uname -m)" >> "$OUTPUT_FILE"

# ── Transport Throughput ──────────────────────────────────────────────────

cat >> "$OUTPUT_FILE" <<'SECTION'
## Transport Throughput

End-to-end HTTP round-trip latency through JSON-RPC and REST transports.
All measurements use loopback (127.0.0.1) to isolate SDK overhead from network latency.

SECTION

# Criterion dirs: transport_jsonrpc_send, transport_jsonrpc_stream, transport_rest_send, etc.
emit_table "transport_"

# ── Protocol Overhead ─────────────────────────────────────────────────────

cat >> "$OUTPUT_FILE" <<'SECTION'
## Protocol Overhead

Serialization and deserialization cost per A2A type. This is the baseline tax
every message pays regardless of transport.

SECTION

# Criterion dirs: protocol_type_serde, protocol_jsonrpc_envelope, protocol_stream_events, protocol_batch
emit_table "protocol_"

# ── Task Lifecycle ────────────────────────────────────────────────────────

cat >> "$OUTPUT_FILE" <<'SECTION'
## Task Lifecycle

TaskStore and EventQueue operations — the backbone of task management.

SECTION

# Criterion dirs: lifecycle_store_save, lifecycle_store_get, lifecycle_store_list, lifecycle_queue, lifecycle_e2e
emit_table "lifecycle_"

# ── Concurrent Agents ─────────────────────────────────────────────────────

cat >> "$OUTPUT_FILE" <<'SECTION'
## Concurrent Agents

Scaling behavior under parallel load — how latency changes as
concurrency increases from 1 to 64 simultaneous operations.

SECTION

# Criterion dirs: concurrent_sends, concurrent_streams, concurrent_store, concurrent_mixed
emit_table "concurrent_"

# ── Realistic Workloads ───────────────────────────────────────────────────

cat >> "$OUTPUT_FILE" <<'SECTION'
## Realistic Workloads

Production-like usage patterns: multi-turn conversations, mixed payloads,
interceptor chains, and connection reuse vs per-request clients.

SECTION

# Criterion dirs: realistic_multi_turn, realistic_payload_complexity, realistic_connection, etc.
emit_table "realistic_"

# ── Error Paths ───────────────────────────────────────────────────────────

cat >> "$OUTPUT_FILE" <<'SECTION'
## Error Paths

Cost of error handling — comparing happy path latency to error path latency.
Production systems spend significant time on error paths; benchmarking only
the happy path gives an incomplete picture.

SECTION

# Criterion dirs: errors_happy_vs_error, errors_task_not_found, errors_malformed_request
emit_table "errors_"

# ── Backpressure ──────────────────────────────────────────────────────────

cat >> "$OUTPUT_FILE" <<'SECTION'
## Streaming & Backpressure

Stream throughput under varying event volumes and consumer speeds.
Reveals buffering and flow-control overhead that synthetic single-event tests miss.

SECTION

# Criterion dirs: backpressure_stream_volume, backpressure_slow_consumer, backpressure_concurrent_streams
emit_table "backpressure_"

# ── Data Volume ───────────────────────────────────────────────────────────

cat >> "$OUTPUT_FILE" <<'SECTION'
## Data Volume Scaling

TaskStore performance at realistic data volumes (1K to 100K tasks).
Shows how store operations scale as data accumulates over time.

SECTION

# Criterion dirs: data_volume_get, data_volume_list, data_volume_save, data_volume_concurrent_reads, data_volume_history_depth
emit_table "data_volume_"

# ── Memory Overhead ───────────────────────────────────────────────────────

cat >> "$OUTPUT_FILE" <<'SECTION'
## Memory Overhead

Heap allocation counts and bytes per operation, measured via a counting
allocator (`#[global_allocator]`). Values represent allocation counts or
bytes — not time — encoded as nanoseconds for Criterion tracking.

| Metric | Unit |
|--------|------|
| `*_alloc_count` | Number of `alloc()` calls per operation |
| `*_bytes_per_payload` | Bytes allocated per operation |

SECTION

# Criterion dirs: memory_serialize, memory_deserialize, memory_history_scaling, memory_bytes_per_payload
emit_table "memory_" "count"

# ── Cross-Language Comparison ─────────────────────────────────────────────

cat >> "$OUTPUT_FILE" <<'SECTION'
## Cross-Language Comparison

Standardized workloads designed to be reproduced identically across all
A2A SDK implementations (Python, Go, JS, Java, C#/.NET).

- All SDKs hit the **same Rust echo server** (eliminates server-side variance)
- All workloads use **identical JSON payloads** from `benches/cross_language/`
- Results use **median ± MAD** to resist outlier pollution

SECTION

# Criterion dirs: cross_language_echo_roundtrip, cross_language_stream_events, etc.
emit_table "cross_language_"

# ── Enterprise Scenarios ─────────────────────────────────────────────────

cat >> "$OUTPUT_FILE" <<'SECTION'
## Enterprise Scenarios

Production-scale workloads modeling real deployments: multi-tenant isolation,
push notification management, eviction under memory pressure, rate limiting,
CORS handling, read/write mix ratios, and large conversation histories.

SECTION

# Criterion dirs: enterprise_multi_tenant, enterprise_push_config, enterprise_eviction, etc.
emit_table "enterprise_"

# ── Production Scenarios ─────────────────────────────────────────────────

cat >> "$OUTPUT_FILE" <<'SECTION'
## Production Scenarios

Full end-to-end workflows exercising the complete SDK pipeline in scenarios
that real-world deployments encounter at scale: task reconnection, cold start
latency, concurrent race conditions, multi-context orchestration, push config
lifecycle, parallel agent bursts, and dispatch routing overhead isolation.

SECTION

# Criterion dirs: production_subscribe_to_task, production_cold_start, production_e2e_orchestration, etc.
emit_table "production_"

# ── Advanced Scenarios ──────────────────────────────────────────────────

cat >> "$OUTPUT_FILE" <<'SECTION'
## Advanced Scenarios

SDK capabilities exercising previously-unbenchmarked paths: tenant resolver
overhead, agent card hot-reload and discovery, subscribe fan-out for
reconnection bursts, streaming artifact accumulation cost (the 90µs/event
bottleneck), pagination full walk, and extended agent card round-trip.

SECTION

# Criterion dirs: advanced_tenant_resolver, advanced_agent_card_hot_reload, advanced_agent_card_discovery, etc.
emit_table "advanced_"

# ── Footer ────────────────────────────────────────────────────────────────

cat >> "$OUTPUT_FILE" <<'FOOTER'
---

## Methodology

All benchmarks use [Criterion.rs](https://github.com/bheisler/criterion.rs),
which provides:

- **Statistical significance testing** — detects real regressions vs noise
- **Warm-up iterations** — avoids cold-start measurement artifacts
- **Median ± MAD** — robust central tendency resistant to outliers
- **Configurable sample sizes** — more iterations for noisy benchmarks

### Measurement rigor

All benchmarks follow these practices for reproducibility:

- **Deterministic inputs**: Fixed task IDs and payloads inside `iter()` — no
  incrementing counters that change HashMap distribution across iterations
- **Setup outside measurement**: Store creation, server startup, and resource
  allocation happen before `iter()`, not inside it
- **`debug_assert!` for invariants**: Correctness checks inside measurement
  loops use `debug_assert!` to avoid string-formatting cost in release builds
- **`black_box()` on inputs and outputs**: Prevents the compiler from
  eliminating measured work through dead-code optimization
- **Tolerance-based allocation assertions**: Memory benchmarks use a 5%
  tolerance instead of exact counts to avoid spurious CI failures from
  serde_json/stdlib version changes
- **Side-effect interceptors**: The interceptor chain benchmark uses
  `CountingInterceptor` (AtomicU64) to verify interceptors are actually
  invoked during measurement — not just optimized away

### What we benchmark

The SDK's value proposition is the **A2A protocol layer and runtime efficiency**,
not agent logic. We benchmark what the SDK owns: transport overhead, serialization
cost, store operations, concurrency scaling, streaming backpressure, error handling,
and memory allocation behavior.

### What we do NOT benchmark

- **Agent intelligence** — LLM quality is an eval problem, not a perf benchmark
- **Network latency** — all benchmarks use loopback (127.0.0.1)
- **TLS handshake** — benchmarks use plaintext HTTP
- **Task completion quality** — needs human-preference evaluation

### Reproducing locally

```bash
# Run all benchmarks
cargo bench -p a2a-benchmarks

# Run a specific module
cargo bench -p a2a-benchmarks --bench transport_throughput

# Save baseline, make changes, then compare
./benches/scripts/run_benchmarks.sh --save
# ... make changes ...
./benches/scripts/run_benchmarks.sh --compare
```

Full HTML reports (with violin plots and comparison overlays) are generated
in `target/criterion/`.
FOOTER

echo "Book page generated: $OUTPUT_FILE"
